import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import {Hanken_Grotesk} from "next/font/google"
import {Sour_Gummy} from "next/font/google"
import "./globals.css";

const hankenGrotesk = Hanken_Grotesk({
  variable: "--font-hanken-grotesk",
  subsets: ["latin"],
});

const sourGummy = Sour_Gummy({
  variable: "--font-sour-gummy",
  subsets: ["latin"]
})

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Refresh 29",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${hankenGrotesk.variable} ${sourGummy.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
